// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWiKDzsR_vEUwqrePVa6IrtAYVGqAizYk',
    appId: '1:85025048975:web:00ebe9fa55a5ed8b7c63fa',
    messagingSenderId: '85025048975',
    projectId: 'movie-app-126a7',
    authDomain: 'movie-app-126a7.firebaseapp.com',
    storageBucket: 'movie-app-126a7.firebasestorage.app',
    measurementId: 'G-8J45BWPTT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGo59qaH2cdySH0-6lHRTqsRZEX5o5fqQ',
    appId: '1:85025048975:android:b559893c8645bf9b7c63fa',
    messagingSenderId: '85025048975',
    projectId: 'movie-app-126a7',
    storageBucket: 'movie-app-126a7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC38Sqn_78mhxdz6T864PoWYVzHmvnIB_I',
    appId: '1:85025048975:ios:4726167e1c9d88417c63fa',
    messagingSenderId: '85025048975',
    projectId: 'movie-app-126a7',
    storageBucket: 'movie-app-126a7.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC38Sqn_78mhxdz6T864PoWYVzHmvnIB_I',
    appId: '1:85025048975:ios:4726167e1c9d88417c63fa',
    messagingSenderId: '85025048975',
    projectId: 'movie-app-126a7',
    storageBucket: 'movie-app-126a7.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );
}
